<?php

/* This file is autogenerated and contains constants specific to current installation */



define("EMAIL_FROM", "email@meetingnotes.io");
define("EMAIL_REALNAME", "meetingnotes.io");
define("EMAIL_SUGGESTIONS", "mysimplegrid_suggestions@mydatalinx.com");
define("MANDRILL_USERNAME", "yoann.maingon@mydatalinx.com");
define("MANDRILL_SMTPKEY", "d3e6c8d4-6ed4-450d-b7a6-521f648972e1");


/* Define the URL root for Neo4j graph database */
define("NEO4J_URL_ROOT", "http://localhost:7474");

/* Define the URL root where to find the application, this could be different in your installation */
define("URL_ROOT", "http://127.0.0.1:8080/BOM3GIT/");

/* Token URL target for Janrain login. Must be absolute url not relative */
define("JANRAIN_TOKEN_URL", URL_ROOT . "openid/rpx-token-url.php");


/* MixPanel metrics tool key */
define("METRICS_MIXPANEL_TOKEN", "01d68a5792f4d51ad1c59b11723e2c1d");

/* Current version of the constantsSpecific */
define("CONSTANTS_SPECIFICS_VERSION", "1.2");


?>